/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rizwan Qureshi
 */
public class DeleteR extends javax.swing.JFrame {

    /**
     * Creates new form DeleteR
     */
    public DeleteR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Donor_Id", "D_Name", "Gender", "Age", "Blood Group", "Country", "Address", "Date", "Mobile"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 470, 153);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("By ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 204, 86, 23);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(134, 203, 86, 25);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 240, 90, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 200, 86, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("By Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 245, 63, 23);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(134, 244, 86, 25);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 200, 90, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 240, 86, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("By Group:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 286, 63, 23);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(134, 285, 86, 25);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(260, 280, 90, 30);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(380, 280, 86, 30);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 255));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(199, 323, 102, 33);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/abstract_colors_bloodstream_red.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     String s=jTextField1.getText();
				if(s.isEmpty())
				{
					JOptionPane.showMessageDialog(null, "The field is empty");
				}
				
				
			try
				{
				 Class.forName("com.mysql.jdbc.Driver");

				 Connection con = DriverManager.getConnection("jdbc:mysql://localhost/blood_bank","root","");
		
				 Statement st = con.createStatement();
				 
				 
				 
			//	String query = "select * from medicine where name='"+textField.getText()+"' ";
				
				 String query = "Delete from d_detail where Donor_Id = '"+Integer.parseInt(jTextField1.getText())+"%' ";
				
				 
				 st.executeUpdate(query);
					String columnNames[] = {"Donor_Id","D_Name","Gender","Age","Blood_Group","Country","Address","Date","Mobile"};
					
					
						
						DefaultTableModel model = new DefaultTableModel();
						model.setColumnIdentifiers(columnNames);
					
					  jTable1.setModel(model);
				  while(rs.next())
				  {
				  
					  
				
						model.addRow(new Object[]{rs.getString("Donor_Id"), rs.getString("D_Name"), rs.getString("Gender"), rs.getString("Age"), rs.getString("Blood_Group"), rs.getString("Country"), rs.getString("Address"), rs.getString("Date"), rs.getString("Mobile")});
					  
					  
					  
					 
				
					  
					 
				  
				 
				  /*else
				  {
					  System.out.println("no result found");
				  }
				  */
				
				 
				}
                                }
				
				catch(Exception ex)
				{
					System.out.println("Error " + ex);	
				}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String b=jTextField2.getText();
        if(b.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The field is empty");
        }

        try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/blood_bank","root","");

            Statement st = con.createStatement();

            //	String query = "select * from medicine where name='"+textField.getText()+"' ";

            String query = "Delete from d_detail where D_Name Like '"+jTextField2.getText()+"%' ";

           st.executeUpdate(query);
            String columnNames[] = {"Donor_Id","D_Name","Gender","Age","Blood_Group","Country","Address","Date","Mobile"};

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);

            jTable1.setModel(model);
            while(rs.next())
            {

                model.addRow(new Object[]{rs.getString("Donor_Id"), rs.getString("D_Name"), rs.getString("Gender"), rs.getString("Age"), rs.getString("Blood_Group"), rs.getString("Country"), rs.getString("Address"), rs.getString("Date"), rs.getString("Mobile")});

                /*else
                {
                    System.out.println("no result found");
                }
                */

            }
        }

        catch(Exception ex)
        {
            System.out.println("Error " + ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String b=jTextField3.getText();
        if(b.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The field is empty");
        }

        try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/blood_bank","root","");

            Statement st = con.createStatement();

            //	String query = "select * from medicine where name='"+textField.getText()+"' ";

            String query = "Delete from d_detail where Blood_Group like '"+jTextField3.getText()+"%' ";

              st.executeUpdate(query);
            String columnNames[] = {"Donor_Id","D_Name","Gender","Age","Blood_Group","Country","Address","Date","Mobile"};

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);

            jTable1.setModel(model);
            while(rs.next())
            {

                model.addRow(new Object[]{rs.getString("Donor_Id"), rs.getString("D_Name"), rs.getString("Gender"), rs.getString("Age"), rs.getString("Blood_Group"), rs.getString("Country"), rs.getString("Address"), rs.getString("Date"), rs.getString("Mobile")});

                /*else
                {
                    System.out.println("no result found");
                }
                */

            }
        }

        catch(Exception ex)
        {
            System.out.println("Error " + ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    String b=jTextField3.getText();
        if(b.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The field is empty");
        }

        try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/blood_bank","root","");

            Statement st = con.createStatement();

            //	String query = "select * from medicine where name='"+textField.getText()+"' ";

            String query = "select * from d_detail where Blood_Group like '"+jTextField3.getText()+"%' ";

            ResultSet  rs=st.executeQuery(query);
            String columnNames[] = {"Donor_Id","D_Name","Gender","Age","Blood_Group","Country","Address","Date","Mobile"};

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);

            jTable1.setModel(model);
            while(rs.next())
            {

                model.addRow(new Object[]{rs.getString("Donor_Id"), rs.getString("D_Name"), rs.getString("Gender"), rs.getString("Age"), rs.getString("Blood_Group"), rs.getString("Country"), rs.getString("Address"), rs.getString("Date"), rs.getString("Mobile")});

                /*else
                {
                    System.out.println("no result found");
                }
                */

            }
        }

        catch(Exception ex)
        {
            System.out.println("Error " + ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Blood1 b=new Blood1();
       b.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String s=jTextField1.getText();
				if(s.isEmpty())
				{
					JOptionPane.showMessageDialog(null, "The field is empty");
				}
				
				
			try
				{
				 Class.forName("com.mysql.jdbc.Driver");

				 Connection con = DriverManager.getConnection("jdbc:mysql://localhost/blood_bank","root","");
		
				 Statement st = con.createStatement();
				 
				 
				 
			//	String query = "select * from medicine where name='"+textField.getText()+"' ";
				
				 String query = "select * from d_detail where Donor_Id like '"+Integer.parseInt(jTextField1.getText())+"%' ";
				
				 
				 ResultSet  rs=st.executeQuery(query);
					String columnNames[] = {"Donor_Id","D_Name","Gender","Age","Blood_Group","Country","Address","Date","Mobile"};
					
					
						
						DefaultTableModel model = new DefaultTableModel();
						model.setColumnIdentifiers(columnNames);
					
					  jTable1.setModel(model);
				  while(rs.next())
				  {
				  
					  
				
						model.addRow(new Object[]{rs.getString("Donor_Id"), rs.getString("D_Name"), rs.getString("Gender"), rs.getString("Age"), rs.getString("Blood_Group"), rs.getString("Country"), rs.getString("Address"), rs.getString("Date"), rs.getString("Mobile")});
					  
					 
				
				 
				}
                                }
				
				catch(Exception ex)
				{
					System.out.println("Error " + ex);	
				}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String b=jTextField2.getText();
        if(b.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "The field is empty");
        }

        try
        {
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/blood_bank","root","");

            Statement st = con.createStatement();

            //	String query = "select * from medicine where name='"+textField.getText()+"' ";

            String query = "select * from d_detail where D_Name like '"+jTextField2.getText()+"%' ";

            ResultSet  rs=st.executeQuery(query);
            String columnNames[] = {"Donor_Id","D_Name","Gender","Age","Blood_Group","Country","Address","Date","Mobile"};

            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columnNames);

            jTable1.setModel(model);
            while(rs.next())
            {

                model.addRow(new Object[]{rs.getString("Donor_Id"), rs.getString("D_Name"), rs.getString("Gender"), rs.getString("Age"), rs.getString("Blood_Group"), rs.getString("Country"), rs.getString("Address"), rs.getString("Date"), rs.getString("Mobile")});

                /*else
                {
                    System.out.println("no result found");
                }
                */

            }
        }

        catch(Exception ex)
        {
            System.out.println("Error " + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteR().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void resize(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
}
